-- MySQL Script generated by MySQL Workbench
-- 09/08/16 19:19:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema book_store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `book_store_books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store_books` ;

CREATE TABLE IF NOT EXISTS `book_store_books` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `book_title` VARCHAR(150) NOT NULL,
  `book_content` LONGTEXT NOT NULL,
  `book_photo` VARCHAR(150) NOT NULL,
  `book_file` VARCHAR(150) NOT NULL,
  `book_cost` MEDIUMTEXT NOT NULL,
  `book_category_id` INT NOT NULL,
  `book_auther_id` MEDIUMTEXT NOT NULL,
  `book_downloads_num` MEDIUMTEXT NOT NULL,
  `book_created_date` TIMESTAMP NOT NULL,
  `book_modified_date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`book_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_store_books_reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store_books_reviews` ;

CREATE TABLE IF NOT EXISTS `book_store_books_reviews` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `review_percent` INT NOT NULL,
  `review_content` TEXT NOT NULL,
  `review_date` TIMESTAMP NOT NULL,
  `review_book_id` INT NOT NULL,
  `review_user_id` INT NOT NULL,
  PRIMARY KEY (`review_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_store_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store_users` ;

CREATE TABLE IF NOT EXISTS `book_store_users` (
  `user_id` MEDIUMTEXT NOT NULL,
  `user_name` VARCHAR(100) NOT NULL,
  `user_username` VARCHAR(100) NOT NULL,
  `user_content` TEXT NOT NULL,
  `user_is_admin` INT NOT NULL,
  `user_is_auther` INT NOT NULL,
  `user_is_user` INT NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `book_store_users_meta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store_users_meta` ;

CREATE TABLE IF NOT EXISTS `book_store_users_meta` (
  `meta_id` INT NOT NULL AUTO_INCREMENT,
  `meta_book_id` INT NOT NULL,
  `meta_user_id` INT NOT NULL,
  `meta_type` INT NOT NULL,
  PRIMARY KEY (`meta_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_store_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store_categories` ;

CREATE TABLE IF NOT EXISTS `book_store_categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_title` VARCHAR(100) NOT NULL,
  `category_content` TEXT NOT NULL,
  `category_user_id` INT NOT NULL,
  `category_photo` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
